### ISSUE TITLE
Farmon megint fejlődik a pet!

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#107]
tothdavid kérdezte, hogy használhat-e petet a farmon, mivel úgy tudtuk, hogy nem fejlődik, ezért mondtuk neki, hogy persze. Ő azonnal szolt, hogy kapja a pet-e az xp.t

Megkért hogy jelentsem én, de a hibát ő találta. Köszönöm,

**Comment by andris155** [comment]
Köszönjük a bejelentést!

**Comment by andris155** [comment]
@Kronox12 tudnál írni a fejlesztőnek?

**Comment by andris155** [comment]
```
  Exp:
    DamageWeightedExperienceDistribution: false
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
    Gain:
      MonsterSpawner: false
```
