### ISSUE TITLE
Nem engedi lerakni a generatort, arra hivatkozva, hogy több van.

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1453]
De nincs.
![2018-01-21_18 49 55](https://user-images.githubusercontent.com/34780638/35197172-022d799c-fedc-11e7-9d08-a9e9bac27eb5.png)

**Comment by andris155** [comment]
```
limit:
  chargingstation: 25
  generator: 25
  batterybank: 20
  quary: 4
  mobgrinder: 10
  solarpanel: 30
  electricfurnace: 25
  harvester: 20
  xptank: 15
  elevator: 50
  reactor: 4
  monitor: 5
  memory: 50
  windturbine: 25
  autocrafter: 5
  tank: 25
  coalliquefactor: 10
```
