### ISSUE TITLE
Információ szöveg

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1902]
Szia. Van a Mobarena-s Információ box, azt kellene átírni erre:
Murder Mystery, Mobarena és más Minigame-ek: /warp eventek 

Valamint ha van más Minigame-es információ, azt kivenni, elegendő ha csak a mobarénas szöveg van átírva. :D

**Comment by andris155** [comment]
```
Broadcaster:
  Enabled: true
  Mode: 0
  Prefix: '&2[Információ]'
  Suffix: ''
  Delay_Seconds: 180
  Messages:
    global:
    - '&fLike-old a facebook oldalunkat!&a https://www.facebook.com/theoldc'
    - '&fCsatlakozz a Facebook csoportunkba!&a https://www.facebook.com/groups/theoldc'
    - '&fMurder Mystery, Mobarena és más Minigame-ek: &a/warp eventek&f!'
    - '&fA területet, ahol építesz &cMINDIG VÉDD LE&f! Mert különben szétrombolhatják!'
    - '&fPvP-zni szeretnél? Írd be, hogy &a/warp pvparénák'
    - '&fMineMarket: &a/warp Támogatás'
    - '&fHa segítség kell, akkor használd: &a/helpop üzenet&f parancsot!'
    - '&fHa egy személynek írsz, akkor használd a &a/m név üzenet &fparancsot!'
    - '&fA szerveren más szervert hirdetni szigorúan &ctilos&f!'
    - '&fWeboldalunk: &ahttps://www.oldcrafters.net/'
    - '&cIsmeretlen teleport kérést csak a saját felelősségedre fogadj el!'
    - '&fAjánlott szerver host:&a https://vgh.hu/'
    - '&fSegítő tagfelvétel:&a https://www.oldcrafters.net/tgf'
    - '&fJelents hibákat, és szerezz ingyen OCD-t: &ahttps://github.com/andris155/TheOld-Crafters'
    - '&fÍrj ötleteket, és szerezz ingyen OCD-t: &ahttps://github.com/andris155/TheOld-Crafters'
    - '&fTudj meg magadról és másokról hasznos információkat a &a/stats &fvagy a &a/stats
      név&f paranccsal!'
    - '&fHasználd a &a/trade név&f parancsot, ha biztonságosan szeretnél kereskedni
      mással!'
    - '&fHallgass &azenéket&f a játékban a &a/music&f paranccsal!'
    - '&fA &a[Szöveg]&f táblák &ajobb klikkel&f használhatóak!'
    - '&fA &a/bolt&f paranccsal értékes dolgok vásárolhatók!'
    - '&fA weboldalak a chat-en kattintással megnyithatók!'
    - '&fSzavazz a szerverre értékes jutalmakért a &a/vote&f paranccsal!'
    - '&fVásárolj értékes fejeket a &a/heads&f menüben!'
    - '&fNem értesz valamit a &aMyPet&f-ben? Olvasd el a &a/warp petparancsok&f helyen
      található leírásokat!'
    - '&fNem tudod, hogyan kell &alevédeni&f? Olvasd el a &a/warp levédés&f helyen
      található leírásokat!'
    - '&fNem tudod, hogyan lehet &apénzt keresni&f? Olvasd el a &a/warp pénz&f helyen
      található leírásokat!'
    - '&fSzeretnél &aliftet&f vagy &akaput&f, de nem tudod, hogyan kell? Olvasd el
      a &a/warp craftbook&f helyen található leírásokat!'
    - '&fPaintball:&a /pb join&f!'
    - '&fJátssz érdekes játékokkal a &a/gb&f parancs beírásával!'
    - '&fDiscord szerverünk:&a https://discord.gg/MRTmV89'
  Sound: none

```
