### ISSUE TITLE
Suggestion: Savsziget /is value limit

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2560]
AcidIsland Savsziget
A /is value ne csak azt írja ki mennyit ér az adott block, hanem, azt is hogy mekkora a korlátozás, azaz hány darabtól nem számol vele a rendszer.

Üdv. KulGery

**Comment by andris155** [comment]
Nem tudom sajnos beállítani.

**Comment by andris155** [comment]
De itt a konfig.
```
# This file lists the values for various blocks that are used to calculate the
# island level. Level = total of all blocks in island boundary / 100.
# Players with the permission acidisland.island.multiplier.# will have their blocks
# multiplied in value by that amount.

# Underwater block multiplier
# If blocks are below sea-level, they can have a higher value. e.g. 2x
# Promotes under-water development if there is a sea. Value can be fractional.
underwater: 1.0

# Value of one island level. Default 100. Minimum value is 1.
levelcost: 100

# Death penalty
# How many block values a player will lose per death.
# Default value of 100 means that for every death, the player will lose 1 level (if levelcost is 100)
# Set to zero to not use this feature
deathpenalty: 100
# Sum team deaths - if true, all the teams deaths are summed
# If false, only the leader's deaths counts
sumteamdeaths: false
# Max deaths
# If player dies more than this, it doesn't count anymore
# Stops players from getting into an impossible situation
maxdeaths: 10
# Reset deaths on island reset
islandresetdeathreset: true
# Reset deaths on team join
teamjoindeathreset: true

# This section lists the limits for any particular block. Blocks over this amount
# are not counted.
# Format:
# MATERIAL: limit or MATERIAL:DATA: limit.
# If DATA is used, there MUST be a corresponding block:data value in the blocks list.
# For example, if you limit Jungle Logs LOG:3, then there must be a value for LOG:3
# in the blocks section. If there is not, then LOG:3 would have no value.
limits:
  COBBLESTONE: 10000
  NETHERRACK: 1000
  #LOG:3: 10
  DIAMOND_BLOCK: 5
  DIAMOND_ORE: 5
  GOLD_BLOCK: 5
  GOLD_ORE: 5
  IRON_ORE: 5
  IRON_BLOCK: 5
  EMERALD_ORE: 5
  EMERALD_BLOCK: 5
  FURNACE: 10
# This section lists the value of a block. Value must be an integer.
# Any blocks not listed will have a value of zero.
# Format is MATERIAL: value or MATERIAL:DATA: value.

blocks:
  ACACIA_DOOR: 1
  ACACIA_STAIRS: 1
  ACACIA_FENCE: 1
  ACACIA_FENCE_GATE: 1
  ACACIA_STAIRS: 2
  ACTIVATOR_RAIL: 10
  AIR: 0
  ANVIL: 10
  ARMOR_STAND: 2
  BANNER: 2
  BEACON: 100
  BED_BLOCK: 1
  BEDROCK: 0
  BEETROOT_BLOCK: 1
  BIRCH_DOOR: 1
  BIRCH_FENCE: 1
  BIRCH_FENCE_GATE: 1
  BIRCH_WOOD_STAIRS: 1
  BLACK_GLAZED_TERRACOTTA: 1
  BLACK_SHULKER_BOX: 1
  BLUE_GLAZED_TERRACOTTA: 1
  BLUE_SHULKER_BOX: 1
  BOAT: 2
  BOAT_ACACIA: 2
  BOAT_BIRCH: 2
  BOAT_DARK_OAK: 2
  BOAT_JUNGLE: 2
  BOAT_SPRUCE: 2
  BONE_BLOCK: 1
  BOOKSHELF: 5
  BREWING_STAND: 20
  BRICK: 5
  BRICK_STAIRS: 5
  BROWN_GLAZED_TERRACOTTA: 1
  BROWN_SHULKER_BOX: 1
  BURNING_FURNACE: 10
  CACTUS: 1
  CAKE_BLOCK: 1
  CARPET: 1
  CAULDRON: 10
  CHEST: 2
  CHORUS_FLOWER: 1
  CHORUS_PLANT: 1
  CLAY: 2
  COAL_BLOCK: 9
  COAL_ORE: 0
  COBBLE_WALL: 1
  COBBLESTONE: 1
  COBBLESTONE_STAIRS: 1
  COCOA: 1
  CONCRETE: 1
  CONCRETE_POWDER: 1
  CYAN_GLAZED_TERRACOTTA: 1
  CYAN_SHULKER_BOX: 1
  DARK_OAK_DOOR: 1
  DARK_OAK_FENCE: 1
  DARK_OAK_FENCE_GATE: 1
  DARK_OAK_STAIRS: 1
  DAYLIGHT_DETECTOR: 10
  DAYLIGHT_DETECTOR_INVERTED: 10
  DEAD_BUSH: 1
  DETECTOR_RAIL: 10
  DIAMOND_BLOCK: 300
  DIODE: 5
  DIODE_BLOCK_OFF: 5
  DIODE_BLOCK_ON: 5
  DIRT: 2
  DISPENSER: 5
  DOUBLE_PLANT: 2
  DOUBLE_STEP: 1
  DOUBLE_STONE_SLAB2: 1
  DRAGON_EGG: 150
  DROPPER: 5
  EMERALD_BLOCK: 150
  EMERALD_ORE: 0
  ENCHANTMENT_TABLE: 150
  END_BRICKS: 2
  ENDER_CHEST: 150
  ENDER_PORTAL_FRAME: 0
  ENDER_PORTAL: 0
  ENDER_STONE: 2
  EXPLOSIVE_MINECART: 10
  FENCE: 1
  FENCE_GATE: 1
  FIRE: 0
  FLOWER_POT: 5
  FROSTED_ICE: 1
  FURNACE: 10
  GLASS: 2
  GLOWSTONE: 1
  GOLD_BLOCK: 150
  GOLD_ORE: 0
  GRASS: 5
  GRASS_PATH: 5
  GRAY_GLAZED_TERRACOTTA: 1
  GRAY_SHULKER_BOX: 1
  GRAVEL: 1
  GREEN_GLAZED_TERRACOTTA: 1
  GREEN_SHULKER_BOX: 1
  HARD_CLAY: 2
  HAY_BLOCK: 2
  HOPPER: 10
  HOPPER_MINECART: 20
  HUGE_MUSHROOM_1: 1
  HUGE_MUSHROOM_2: 1
  ICE: 0
  IRON_BLOCK: 10
  IRON_DOOR_BLOCK: 5
  IRON_FENCE: 5
  IRON_ORE: 0
  IRON_PLATE: 5
  IRON_TRAPDOOR: 1
  ITEM_FRAME: 2
  JACK_O_LANTERN: 1
  JUKEBOX: 10
  JUNGLE_DOOR: 1
  JUNGLE_FENCE: 1
  JUNGLE_FENCE_GATE: 1
  JUNGLE_WOOD_STAIRS: 1
  LADDER: 1
  LAPIS_BLOCK: 10
  LAPIS_ORE: 0
  LAVA: 0
  LEAVES_2: 1
  LEAVES: 1
  LEVER: 1
  LIGHT_BLUE_GLAZED_TERRACOTTA: 1
  LIGHT_BLUE_SHULKER_BOX: 1
  LIME_GLAZED_TERRACOTTA: 1
  LIME_SHULKER_BOX: 1
  LOG: 1
  #Other log types - examples
  #LOG:3: 2
  LOG_2: 1
  LONG_GRASS: 1
  MAGENTA_GLAZED_TERRACOTTA: 1
  MAGENTA_SHULKER_BOX: 1
  MAGMA: 1
  MELON_BLOCK: 1
  MELON_STEM: 1
  MINECART: 10
  MOB_SPAWNER: 0
  MOSSY_COBBLESTONE: 2
  MYCEL: 5
  NETHER_BRICK: 2
  NETHER_BRICK_STAIRS: 2
  NETHER_FENCE: 2
  NETHER_STALK: 1
  NETHER_WART_BLOCK: 2
  NETHERRACK: 1
  NOTE_BLOCK: 10
  OBSERVER: 1
  OBSIDIAN: 10
  ORANGE_GLAZED_TERRACOTTA: 1
  ORANGE_SHULKER_BOX: 1
  PACKED_ICE: 5
  PAINTING: 2
  PINK_GLAZED_TERRACOTTA: 1
  PINK_SHULKER_BOX: 1
  PISTON_BASE: 2
  PISTON_STICKY_BASE: 2
  PORTAL: 0
  POWERED_MINECART: 10
  POWERED_RAIL: 10
  PRISMARINE: 10
  PUMPKIN_STEM: 1
  PUMPKIN: 1
  PURPLE_GLAZED_TERRACOTTA: 1
  PURPLE_SHULKER_BOX: 1
  PURPUR_BLOCK: 1
  PURPUR_DOUBLE_SLAB: 1
  PURPUR_PILLAR: 1
  PURPUR_SLAB: 1
  PURPUR_STAIRS: 1
  QUARTZ_BLOCK: 1
  QUARTZ_ORE: 0
  QUARTZ_STAIRS: 1
  QUARTZ: 1
  RAILS: 1
  RED_GLAZED_TERRACOTTA: 1
  RED_MUSHROOM: 1
  RED_NETHER_BRICK: 2
  RED_ROSE: 1
  RED_SANDSTONE: 1
  RED_SANDSTONE_STAIRS: 1
  RED_SHULKER_BOX: 1
  REDSTONE_BLOCK: 10
  REDSTONE_COMPARATOR_OFF: 10
  REDSTONE_COMPARATOR_ON: 10
  REDSTONE_COMPARATOR: 10
  REDSTONE_LAMP_OFF: 10
  REDSTONE_LAMP_ON: 10
  REDSTONE_ORE: 0
  REDSTONE_TORCH_OFF: 5
  REDSTONE_TORCH_ON: 5
  REDSTONE_WIRE: 1
  SAND: 0
  SANDSTONE: 0
  SANDSTONE_STAIRS: 1
  SEA_LANTERN: 1
  SIGN_POST: 1
  SILVER_GLAZED_TERRACOTTA: 1
  SILVER_SHULKER_BOX: 1
  SKULL: 10
  SLIME_BLOCK: 10
  SMOOTH_BRICK: 2
  SMOOTH_STAIRS: 2
  SNOW_BLOCK: 1
  SOIL: 2
  SOUL_SAND: 2
  SPONGE: 10
  SPRUCE_DOOR: 1
  SPRUCE_FENCE: 1
  SPRUCE_FENCE_GATE: 1
  SPRUCE_WOOD_STAIRS: 1
  STAINED_CLAY: 2
  STAINED_GLASS: 2
  STAINED_GLASS_PANE: 1
  STATIONARY_LAVA: 0
  STATIONARY_WATER: 0
  STEP: 1
  STONE: 1
  STONE_BUTTON: 1
  STONE_PLATE: 2
  STORAGE_MINECART: 10
  SUGAR_CANE_BLOCK: 1
  THIN_GLASS: 1
  TNT: 5
  TORCH: 2
  TRAP_DOOR: 5
  TRAPPED_CHEST: 10
  TRIPWIRE_HOOK: 2
  TRIPWIRE: 2
  VINE: 1
  WALL_SIGN: 1
  WATER_LILY: 5
  WEB: 10
  WHEAT: 1
  WHITE_GLAZED_TERRACOTTA: 1
  WHITE_SHULKER_BOX: 1
  WOOD: 1
  WOOD_BUTTON: 1
  WOOD_DOOR: 1
  WOOD_DOUBLE_STEP: 1
  WOOD_PLATE: 1
  WOOD_STAIRS: 1
  WOOD_STEP: 1
  WOODEN_DOOR: 1
  WOOL: 1
  WORKBENCH: 1
  YELLOW_FLOWER: 1
  YELLOW_GLAZED_TERRACOTTA: 1
  YELLOW_SHULKER_BOX: 1
  
  
```
