### ISSUE TITLE
HungerGames hibák

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2970]
https://www.spigotmc.org/resources/hungergames.65942/

Ha még nincs lefordítva, és valaki szeretné gyakorolni, lefordíthatná a Hungergames-t. :D :money_mouth_face:

**Comment by Huntermaster0** [comment]
Csak a lang.yml kell?

**Comment by andris155** [comment]
igen. A többi fordítást letudjuk mi is fordítani, mert nem sok.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/blob/master/Fordítások/HungerGames/language.yml

**Comment by Huntermaster0** [comment]
Lassan kész, csak nem githubon írom, mert hamarabb kezdtem.

**Comment by andris155** [comment]
Be lehet illeszteni Notepad++-ból is Github-ra. :D

**Comment by Huntermaster0** [comment]
Csináltam neki egy Pullt, #2971

**Comment by MrZero1** [comment]
![2019-06-15_18 55 10](https://user-images.githubusercontent.com/29709854/59554762-6e573f00-8fa8-11e9-822e-34ebccb5e7da.png)

Ezeket kétszer írta ki. Gondolom alapból nem így kéne lennie.

Kites részt lelehetne tiltani? Felesleges kiteket választani a játék előtt.

Aranyalmákat és a véggyöngyöt kilehetne venni azokból a cuccokból, amiket a ládákba rak random?

**Comment by andris155** [comment]
Ezek a beállítási lehetőségek benne.
```
# 
# Revamped by: ShaneBee
# 
# Issues: Please report issues on the BitBucket issue tracker @ https://bitbucket.org/ShaneBeeStudios/hungergames/issues?status=new&status=open
# Updates: Can be found on SpigotMC @ https://www.spigotmc.org/resources/hungergames.65942/
# 
# More Info: See the wiki for more info on this config @ https://bitbucket.org/ShaneBeeStudios/HungerGames/wiki/Config.yml

settings:
  teleport-at-end-time: 30
  spawn-mobs: true
  spawn-mobs-interval: 35
  free-roam: 25
  trackingstick-uses: 8
  players-for-trackingstick: 5
  max-chestcontent: 5
  teleport-at-end: false
  max-team-size: 3
  bossbar-countdown: true
  globalexit: survivalgames:362:58:-631:-6.7500033:-2.100004
  min-chestcontent: 1
  max-bonus-chestcontent: 5
  min-bonus-chestcontent: 1
reward:
  enabled: true
  cash: 500
  commands:
  - none
  messages:
  - none
random-chest:
  enabled: false
  interval: 30
  max-chestcontent: 9
rollback:
  allow-block-break: false
  fix-leaves: true
  prevent-trampling: true
  editable-blocks:
  - GRASS
  - TALL_GRASS
  - GRASS_BLOCK
  - DIRT
  - COBBLESTONE
  - OAK_PLANKS
  - SANDSTONE
  - WHITE_WOOL
  - STONE_BRICKS
  - GLASS_PANE
  protect-during-cooldown: true
kits:
  bowman:
    permission: none
    helmet: LEATHER_HELMET color:red
    chestplate: LEATHER_CHESTPLATE color:red
    leggings: LEATHER_LEGGINGS color:red
    boots: LEATHER_BOOTS color:red
    items:
    - BOW name:&2Lucky_Bow
    - ARROW 64 name:&aLucky_Arrow
    - POTION:HEAL:60:0 2 name:&bHealing
  survivor:
    permission: none
    helmet: LEATHER_HELMET
    chestplate: LEATHER_CHESTPLATE color:green
    leggings: LEATHER_LEGGINGS color:green
    boots: LEATHER_BOOTS
    items:
    - STONE_SWORD 1 name:&7Survival_Sword
    - BREAD 4 name:&6Peasant's_Bread
    - POTION:HEAL:60:0 2 name:&bHealing
  pro:
    permission: none
    helmet: TURTLE_HELMET name:&2Turtle_Shell
    items:
    - IRON_SWORD 1
    - BREAD 4 name:&8Pro_Bread
    - POTION:HEAL:60:1 2 name:&bSuper_Healing
  ninja:
    permission: none
    helmet: LEATHER_HELMET color:black
    chestplate: LEATHER_CHESTPLATE color:black name:&7Ninja-Jacket lore:&6Ninja-Stealth-Suit:&4-------------
      enchant:PROTECTION_FIRE
    leggings: LEATHER_LEGGINGS color:black
    boots: LEATHER_BOOTS color:black enchant:PROTECTION_FALL
    items:
    - POTION:HEAL:60:1 2 name:&bSuper_Healing
    potion-effects:
    - SPEED:1:forever
  stupidclass:
    permission: hg.vip
    items:
    - IRON_SWORD 1 enchant:DAMAGE_ALL:2 enchant:DAMAGE_UNDEAD:2 name:&bOP_&6Sword?
    - BREAD 4
    - POTION:HEAL:60:2 2 name:&bSuper_Duper_Healing
    potion-effects:
    - FIRE_RESISTANCE:2:forever
world-border:
  enabled: false
  initiate-on-start: true
  countdown-start: 60
  countdown-end: 30
  final-border-size: 30
  center-on-first-spawn: true
```
