### ISSUE TITLE
Luckyblock

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3599]
**Szerver**: Survi Sav

Nem jó a luckyblock, baromi szegényes. Esetleg lehetne valamit kezdeni vele. (plugin?)

**Comment by andris155** [comment]
Mi az, hogy szegényes??

**Comment by andris155** [comment]
Itt a konfig. Ennyi az összes beállítás hozzá. Újat nem lehet hozzáadni.
```yml
world-blacklist:
- world2_nether
- world2_the_end
chance: 2
debug: false
events:
  Cooked Food: true
  Golden Apples: true
  Diamond Block with Lightning: true
  Stained Clay Pillar with Diamond Block on top: true
  Emerald Block: true
  Iron Block: true
  Tamed Dogs: true
  Tamed Cats: true
  Valuables: true
  Lucky Sword: false
  XP Rain: true
  Lucky Helmet: false
  Lucky Chestplate: false
  Lucky Leggings: false
  Lucky Boots: false
  Lucky Potions: true
  Unlucky Potions: true
  Cake: true
  I am Groot: true
  Raw Food: true
  Fish: true
  Wandering Trader: true
  Mister Rainbow: true
  Chicken Rain: true
  Dyes: true
  Hay there: true
  Cookies: true
  jeb Sheep: true
  Villager Number X: false
  PotatOS: true
  Jerry the Slime: true
  Charged Creeper: true
  Witch and Bats: true
  Explosion: true
  Void Hole: false
  Anvil Rain: true
  Enclosed Water Pool: true
  TNT Rain: true
  Flying Creepers: true
  Flying TNT: true
  Normal and Fake Diamond Block: true
  Bryan: false
  Walshrus: false
  Up up and away: true
  Giant Slime: false
  Cobwebs: true
  Reapers: true
  Iron Golem Invasion: true
  Lucky Pickaxe: false
  Lucky Axe: false
  Angry Zombie Pigmen: true

```
