### ISSUE TITLE
Enchant-os Kitek

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#461]

**Comment by andris155** [comment]
```
  VIP:
    delay: 1200
    items:
    - 306 1 Protection:2 Unbreaking:3
    - 307 1 Protection:2 Unbreaking:3
    - 308 1 Protection:2 Unbreaking:3
    - 309 1 Protection:2 Unbreaking:3
    - 272 1 Smite:4 Fire Aspect:2
    - 261 1 Power:3
    - 322:1 1
    - 368 1
  Elit:
    delay: 1800
    items:
    - IRON_HELMET 1 protection_environmental:4 durability:3
    - IRON_CHESTPLATE 1 protection_environmental:4 durability:3
    - IRON_BOOTS 1 protection_environmental:4 durability:3
    - IRON_LEGGINGS 1 protection_environmental:4 durability:3
    - IRON_SWORD 1 damage_all:3 fire_aspect:2
    - BOW 1 arrow_damage:3
    - 373:16393 1
    - 373:16389 2
    - GOLDEN_APPLE:1 3
    - ENDER_PEARL 3
  Prémium:
    delay: 1800
    items:
    - DIAMOND_HELMET 1 protection_environmental:2 durability:3
    - DIAMOND_CHESTPLATE 1 protection_environmental:2 durability:3
    - DIAMOND_LEGGINGS 1 protection_environmental:2 durability:3
    - DIAMOND_BOOTS 1 protection_environmental:2 durability:3
    - DIAMOND_SWORD 1 damage_all:3 fire_aspect:2
    - BOW 1 arrow_damage:4
    - 373:16393 4
    - 373:16389 3
    - 373:16418 2
    - GOLDEN_APPLE:1 5
    - ENDER_PEARL 5
  Old:
    delay: 1200
    items:
    - 310 1 Protection:2 Unbreaking:4
    - 311 1 Protection:2 Unbreaking:4
    - 312 1 Protection:2 Unbreaking:4
    - 313 1 Protection:2 Unbreaking:4
    - 276 1 Sharpness:4
    - 261 1 Power:5
    - 373:16393 6
    - 373:16389 5
    - 373:16418 4
    - 322:1 10
    - 368 10
  Alap:
    delay: 30
    items:
    - 302 1 Protection:1
    - 303 1 Protection:1
    - 304 1 Protection:1
    - 305 1 Protection:1
    - 272 1 FireAspect:1
    - 261 1
    - 262 64
    - 260 64
  Kezdő:
    delay: 120
    items:
    - 302 1 Protection:2
    - 303 1 Protection:2
    - 304 1 Protection:2
    - 305 1 Protection:2
    - 272 1 FireAspect:2
    - 261 1
    - 262 128
    - 364 16
  Haladó:
    delay: 300
    items:
    - 306 1 Protection:2
    - 307 1 Protection:2
    - 308 1 Protection:2
    - 309 1 Protection:2
    - 267 1 FireAspect:1 Unbreaking:1
    - 261 1
    - 262 128
    - 364 32
    - 322 5
  Középhaladó:
    delay: 450
    items:
    - 306 1 Protection:2
    - 307 1 Protection:2
    - 308 1 Protection:2
    - 309 1 Protection:2
    - 267 1 FireAspect:2 Unbreaking:1
    - 261 1 Flame:1
    - 262 16
    - 322 10
    - 364 32
  Profi:
    delay: 450
    items:
    - 306 1 Protection:2 Unbreaking:1
    - 307 1 Protection:2 Unbreaking:1
    - 308 1 Protection:2 Unbreaking:1
    - 309 1 Protection:2 Unbreaking:1
    - 267 1 FireAspect:2 Unbreaking:1
    - 261 1 Flame:1
    - 262 16
    - 364 32
    - 322 10
  Katona:
    delay: 720
    items:
    - 306 1 Protection:3
    - 307 1 Protection:3
    - 308 1 Protection:3
    - 309 1 Protection:3
    - 267 1 FireAspect:1 Knockback:1
    - 261 1 Punch:1
    - 262 32
    - 322:1 1
    - 364 32
  Kiskirály:
    delay: 900
    items:
    - 306 1 Protection:3 Unbreaking:2
    - 307 1 Protection:3 Unbreaking:2
    - 308 1 Protection:3 Unbreaking:2
    - 309 1 Protection:3 Unbreaking:2
    - 267 1 FireAspect:2 Knockback:1 Unbreaking:2
    - 261 1 Punch:1 Unbreaking:1
    - 262 32
    - 322:1 3
    - 364 32
  Király:
    delay: 1200
    items:
    - 310 1 Protection:2
    - 311 1 Protection:2
    - 312 1 Protection:2
    - 313 1 Protection:2
    - 276 1 Knockback:1 Unbreaking:2
    - 261 1 Flame:1 Unbreaking:1
    - 262 64
    - 322:1 3
    - 364 32
  Megváltó:
    delay: 1350
    items:
    - 310 1 Protection:2 Unbreaking:1
    - 311 1 Protection:2 Unbreaking:1
    - 312 1 Protection:2 Unbreaking:1
    - 313 1 Protection:2 Unbreaking:1
    - 276 1 FireAspect:2 Knockback:1 Unbreaking:2
    - 261 1 Punch:2 Unbreaking:1
    - 262 32
    - 322:1 4
    - 364 32
  Isten:
    delay: 1800
    items:
    - 310 1 Protection:3 Unbreaking:2
    - 311 1 Protection:3 Unbreaking:2
    - 312 1 Protection:3 Unbreaking:2
    - 313 1 Protection:3 Unbreaking:2
    - 276 1 Sharpness:2 Knockback:2 FireAspect:2
    - 261 1 Punch:2 Flame:1 Unbreaking:2
    - 262 64
    - 322:1 6
  Menekült:
    delay: 600
    items:
    - DIAMOND_HELMET 1
    - IRON_CHESTPLATE 1
    - IRON_LEGGINGS 1
    - DIAMOND_BOOTS 1
    - DIAMOND_SWORD 1
    - GOLDEN_APPLE 10
    - 373:16393 1
    - 373:16418 1
  Warrior:
    delay: 900
    items:
    - IRON_HELMET 1 protection_environmental:2 oxygen:1
    - IRON_CHESTPLATE 1 protection_environmental:2
    - IRON_LEGGINGS 1 protection_environmental:2
    - IRON_BOOTS 1 protection_environmental:2
    - IRON_SWORD 1 damage_all:2 durability:3
    - GOLDEN_APPLE:1 1
    - 373:8201 1
    - 373:16418 1
  Lövész:
    delay: 700
    items:
    - CHAINMAIL_HELMET 1 protection_projectile:3 oxygen:1
    - CHAINMAIL_CHESTPLATE 1 protection_projectile:3
    - CHAINMAIL_LEGGINGS 1 protection_projectile:3
    - CHAINMAIL_BOOTS 1 protection_projectile:4
    - STONE_SWORD 1 damage_all:3
    - BOW 1 arrow_damage:2
    - ARROW 64
    - ARROW 64
    - 373:8201 1
  Istenek:
    delay: 432000
    items:
    - DIAMOND_HELMET 1 name:&b&l˘°Istenek_Sisakja!°˘ protection_environmental:2 protection_fire:4 durability:3 oxygen:2
    - DIAMOND_CHESTPLATE 1 name:&b&l˘°Istenek_Mellvértje!°˘ protection_environmental:3 durability:3 thorns:1
    - DIAMOND_LEGGINGS 1 name:&b&l˘°Istenek_Lábszárvédője!°˘ protection_environmental:4
    - DIAMOND_BOOTS 1 name:&b&l˘°Istenek_Csizmája!°˘ protection_environmental:3 protection_fall:4 durability:3
    - DIAMOND_SWORD 1 name:&b&l˘°Istenek_Kardja!°˘ damage_all:5 damage_undead:5 durability:2 fire_aspect:2
    - DIAMOND_AXE 1 name:&b&l˘°Istenek_Baltája!°˘ damage_all:5 damage_undead:5
    - GOLD_HOE 1 name:Arész_kaszája lore:Ezzel_hatalmasat_üthetsz_ellenségedre! silk_touch:1
    - DIAMOND_HOE 1 fire_aspect:2 knockback:2
    - BOW 1 name:&b&l˘°Istenek_Íja!°˘ arrow_damage:4 arrow_knockback:2
  Fegyver:
    delay: 3600
    items:
    - DIAMOND_SWORD 1 damage_all:3 durability:3 knockback:2 fire_aspect:2
    - BOW 1 arrow_damage:4 arrow_fire:1
    - GOLDEN_APPLE:1 3
    - 373:8201 1
    - ARROW 32
  Proletár:
    delay: 1800
    items:
    - GOLD_HELMET 1 protection_environmental:2
    - IRON_CHESTPLATE 1 protection_environmental:2
    - DIAMOND_LEGGINGS 1 protection_environmental:2
    - DIAMOND_BOOTS 1 protection_environmental:2 protection_fall:2
    - ENDER_PEARL 3
    - GOLDEN_APPLE 24
    - DIAMOND_SPADE 1 name:Szuper_Lapát dig_speed:3
  Őrző:
    delay: 1800
    items:
    - IRON_HELMET 1 protection_environmental:3 durability:2
    - IRON_CHESTPLATE 1 protection_environmental:3 durability:2
    - IRON_LEGGINGS 1 protection_environmental:3 durability:2
    - IRON_BOOTS 1 protection_environmental:3 durability:2
    - IRON_SWORD 1 damage_all:4 fire_aspect:2
    - GOLDEN_APPLE:1 6
    - ENDER_PEARL 3
    - 373:8201 1
  Szanitéc:
    delay: 1800
    items:
    - DIAMOND_HELMET 1
    - DIAMOND_CHESTPLATE 1
    - DIAMOND_LEGGINGS 1
    - DIAMOND_BOOTS 1
    - DIAMOND_SWORD 1 durability:3 knockback:2
    - BOW 1 arrow_damage:3
    - GOLDEN_APPLE 8
    - ARROW 16
    - 373:8197 4
  Aqua:
    delay: 2000
    items:
    - IRON_HELMET 1 protection_fire:3 durability:3
    - IRON_CHESTPLATE 1 protection_environmental:4 durability:3 thorns:2
    - IRON_LEGGINGS 1 protection_environmental:4 durability:3
    - DIAMOND_BOOTS 1 protection_environmental:4 durability:3
    - DIAMOND_SWORD 1 damage_all:4
    - BOW 1 arrow_damage:4 arrow_fire:1
    - GOLDEN_APPLE:1 8
    - ENDER_PEARL 2
    - ARROW 64
    - ARROW 64
    - 373:8201 3
    - 373:8193 2
    - 373:8197 1
  Gróf:
    delay: 2000
    items:
    - GOLD_HELMET 1 protection_environmental:4 durability:3
    - GOLD_CHESTPLATE 1 protection_environmental:4 durability:3
    - GOLD_LEGGINGS 1 protection_environmental:4 durability:3
    - GOLD_BOOTS 1 protection_environmental:4 durability:3
    - DIAMOND_SWORD 1 fire_aspect:2 durability:3 knockback:2
    - BOW 1 arrow_damage:5 arrow_knockback:2
    - GOLDEN_APPLE 16
    - GOLDEN_APPLE:1 3
    - ARROW 64
    - ARROW 64
    - ARROW 64
    - 373:8201 2
    - 373:8194 2
```
