### ISSUE TITLE
Segítő+ PE szerverekre

### ISSUE THREAD

**Issue by PEszem** [andris155/TheOld-Crafters#541]
Szia.Javasolnám PE szerverekre a _**segítő+**_ rangot.Segítené sokban a munkám.Csak a banjoggal kellene több mint a segítőnek.

**Comment by andris155** [comment]
és mit tudjon?

**Comment by PEszem** [comment]
Segítő jogok plusz ban.

**Comment by DragleX** [comment]
Én is szeretném ha lenne ilyen rang.

**Comment by ChorsyumX** [comment]
Támogatnám ezt a feltevést.

**Comment by Fr3lly** [comment]
Szerintem nagyon jól jönne a Segítő+ 
-Legyen ilyen jogai:
-/tpall
-/tphere
-/tempban
- és Interact jog.

**Comment by Mousking** [comment]
Szerintem /ban, /ban-ip, /bancidbyname, /tempban, /pardon, pardon-ip joggal bővülhetne, én ezt javaslom.

**Comment by DragleX** [comment]
Egy usrinfo jog is kellene ha már van ban joga.

**Comment by andris155** [comment]
Ennyi erővel már moderátor is lehetne...

**Comment by PEszem** [comment]
Elég a ban jog

**Comment by ChorsyumX** [comment]
Egyetértek. Rendelkezzen a ban joggal.

2017. márc. 13. 19:20 ezt írta ("PEszem" <notifications@github.com>):

**Comment by andris155** [comment]
```
Segito+:
  inheritance:
  - Segito
  permissions:
  - pocketmine.command.ban
  - pocketmine.command.bancid
  - pocketmine.command.bancidbyname
  - pocketmine.command.banipbyname
  - essentials.ban
  - pocketmine.command.pardoncid
  - pocketmine.command.unban
  - essentials.tempban
```
